name = "erichaupt-com"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://iazyviaqccusjrzuluyo.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_sdhRfh_9FOq7cqXDFqZSgQ_VVBypXSK"
